version : '3'

services:
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: trucorp-web-2.0
    ports:
      - 7000:80
  db:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306